import React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Dashboard layout for Next Pizza Shop Generated by Next.js',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      DASHBOARD HEADER
      <body>{children}</body>
    </html>
  );
}
